server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: donor-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/donors/**
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/inventory/**
        - id: request-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/requests/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
