server:
  port: 8082

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mariadb://localhost:3306/bloodbank_inventory?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
