server:
  port: 8090

spring:
  application:
    name: request-service
  datasource:
    url: jdbc:postgresql://localhost:5432/bloodbank_request
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

inventory:
  service:
    url: http://localhost:8082

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
