server:
  port: 8090

spring:
  application:
    name: request-service
  datasource:
    url: jdbc:mariadb://localhost:3306/bloodbank_request
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

inventory:
  service:
    url: http://localhost:8082

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
